// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: bkgrpc.proto

package bkgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StringServicesClient is the client API for StringServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StringServicesClient interface {
	Concat(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*StringResponse, error)
	Diff(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*StringResponse, error)
	HealtStatus(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type stringServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewStringServicesClient(cc grpc.ClientConnInterface) StringServicesClient {
	return &stringServicesClient{cc}
}

func (c *stringServicesClient) Concat(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*StringResponse, error) {
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, "/bkgrpc.StringServices/Concat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stringServicesClient) Diff(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*StringResponse, error) {
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, "/bkgrpc.StringServices/Diff", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stringServicesClient) HealtStatus(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/bkgrpc.StringServices/HealtStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StringServicesServer is the server API for StringServices service.
// All implementations must embed UnimplementedStringServicesServer
// for forward compatibility
type StringServicesServer interface {
	Concat(context.Context, *StringRequest) (*StringResponse, error)
	Diff(context.Context, *StringRequest) (*StringResponse, error)
	HealtStatus(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedStringServicesServer()
}

// UnimplementedStringServicesServer must be embedded to have forward compatible implementations.
type UnimplementedStringServicesServer struct {
}

func (UnimplementedStringServicesServer) Concat(context.Context, *StringRequest) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Concat not implemented")
}
func (UnimplementedStringServicesServer) Diff(context.Context, *StringRequest) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Diff not implemented")
}
func (UnimplementedStringServicesServer) HealtStatus(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealtStatus not implemented")
}
func (UnimplementedStringServicesServer) mustEmbedUnimplementedStringServicesServer() {}

// UnsafeStringServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StringServicesServer will
// result in compilation errors.
type UnsafeStringServicesServer interface {
	mustEmbedUnimplementedStringServicesServer()
}

func RegisterStringServicesServer(s grpc.ServiceRegistrar, srv StringServicesServer) {
	s.RegisterService(&StringServices_ServiceDesc, srv)
}

func _StringServices_Concat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StringServicesServer).Concat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bkgrpc.StringServices/Concat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StringServicesServer).Concat(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StringServices_Diff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StringServicesServer).Diff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bkgrpc.StringServices/Diff",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StringServicesServer).Diff(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StringServices_HealtStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StringServicesServer).HealtStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bkgrpc.StringServices/HealtStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StringServicesServer).HealtStatus(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StringServices_ServiceDesc is the grpc.ServiceDesc for StringServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StringServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bkgrpc.StringServices",
	HandlerType: (*StringServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Concat",
			Handler:    _StringServices_Concat_Handler,
		},
		{
			MethodName: "Diff",
			Handler:    _StringServices_Diff_Handler,
		},
		{
			MethodName: "HealtStatus",
			Handler:    _StringServices_HealtStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bkgrpc.proto",
}
